version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/ssl/certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt:ro
      - ~/ssl/private/selfsigned.key:/etc/ssl/private/selfsigned.key:ro
    
    depends_on:
      - react-app
