name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            # Проверяем свободное место
            df -h
            
            # Очищаем Docker-ресурсы
            docker system prune -f --all
            docker volume prune -f
            docker builder prune -f --all
            
            # Останавливаем и очищаем проект
            cd frontend
            git pull origin main
            docker-compose down --remove-orphans
            docker-compose up -d
          "